### ISSUE TITLE
ZenjectException: Unable to resolve 'GameObject' while building object with type 'GameObjectAssetLoader'

### ISSUE THREAD

**Issue by BernEugen** [altunsercan/AddressableLoading#1]
Hello.
I did everything according to your documentation but always getting an error:

_ZenjectException: Unable to resolve 'GameObject' while building object with type 'GameObjectAssetLoader'._

![Error](https://user-images.githubusercontent.com/3944961/83390421-7c40e280-a3fa-11ea-8d6d-72755de767e2.png)

I've tried both options:
Method 1 - using AddressablePreloadListInstaller
![Method_1](https://user-images.githubusercontent.com/3944961/83390390-6df2c680-a3fa-11ea-831c-b91990c72664.png)

Method 2 - using MonoInstaller and manually bind the AssetLoaders
![Method_2](https://user-images.githubusercontent.com/3944961/83390413-777c2e80-a3fa-11ea-81b6-df1800fde85c.png)

Unity 2019.3.11f1
AddressableLoading v0.0.2
Extenject Version 9.2.0 / Version 9.1.0

Thank you.

**Comment by altunsercan** [comment]
In both methods you bind GameObjectAssetLoader to your container not GameObject. So you cannot do this.
```C#
[Inject] private GameObject gameObject;
```

You need to either use something like this
```C#
[Inject(Id="myPrefab")]GameObjectAssetLoader prefabLoader;

public void Initialize()
{
    GameObject prefab = prefabLoader.LoadedAsset;
}
```
or Bind GameObject in installer
```C#
Container.Bind<GameObject>().FromResolveGetter<GameObjectLoader>("myPrefab", loader=>loader.LoadedAsset).AsSingle();
```

Also congratulations on opening the first issue. I haven't replicated your problem in my computer. So if this doesn't help let me know. I can take a look later to replicate it.

**Comment by BernEugen** [comment]
Thanks for your reply.
The thing is that I don't understand how to use your classes. I would very much appreciate if you add a sample. For instance, a Unity project with: an addressable prefab, a scene, an installer/settingsInstaller where the prefab is binded, and a script where we load the binded addressable to the scene as a GameObject.

**Comment by altunsercan** [comment]
Added a sample folder. You have to provide the addressable prefab yourself. I structured this git repo as a UPM package so it could be easily added into project with git url. I don't think I can provide addressables with UPM package. 

Note that I made this repo after receiving a lot of questions in Extenject gitter community. I made DecoratableKernel implementation for Extenject which recently got merged. This would be much easier with that implementation. So I would suggest taking a look at the source and understand the methodology itself.

I also plan on working on Async support for Extenject. So after that is completed this repo will be obsolete because there will be support for adressables in Extenject itself.

**Comment by BernEugen** [comment]
It worked.
Thank you for the example and clarification.
I am looking forward to having this feature as a part of Extenject.

**Comment by DrebotArtem** [comment]
Hello. Thanks for your work. I have same probjem. I opened your example. The prefab loads, but the injection doesn't work.
I added this code to my prefab, but I get a Null message in the console. Why? How to properly use prefab injection?

```
public class MonoTestPrefab : MonoBehaviour
{
  [Inject] Contexts _contexts;

  public void Start()
  {
    Debug.LogWarning(_contexts);
  }
}
```

**Comment by altunsercan** [comment]
Hi @DrebotArtem ,
Its been a while since I looked at this repo. But if I remember correctly, I am only loading the assets (in your case prefabs). Instantiating it within Zenject's workflow is not part of the package. 

In general if you want to instantiate a prefab with injections working, you should not use GameObject.Instantiate if that is what you are using. First item in the "gotchas" section mentions that.
https://github.com/modesttree/Zenject#general-guidelines--recommendations--gotchas--tips-and-tricks

Quickest way would be to use `Container.InstantiatePrefab(loader.LoadedAsset);`. That should inject into prefab.
https://github.com/modesttree/Zenject/blob/31f06cf81043f04301b1072ec81922b64149ea34/UnityProject/Assets/Plugins/Zenject/Source/Main/DiContainer.cs#L2008

If you want it to be done via factory, you would need to add it in your bindings. One way to do it would look like this.
```csharp
Container.BindFactory<Enemy, Enemy.Factory>().FromResolveGetter<GameObjectLoader>("myPrefab", loader=>{
    var instance = Container.InstantiatePrefab(loader.LoadedAsset);
    return instance.GetComponent<Enemy>();
}).AsSingle();
```
I am not 100% if above binding will work. Haven't tested it. But like I said, this is a how do you "instantiate a prefab in Zenject question". There are many ways to do it.

**Comment by altunsercan** [comment]
Also async support I mentioned before has been added to zenject for a while now.
https://github.com/modesttree/Zenject/blob/master/Documentation/Async.md

It is not directly addressable related, but since Addressable loading ins async, it covers it too.

**Comment by DrebotArtem** [comment]
Thanks a lot for such a quick response. But the thing is, I can't use Container.Instantiate. I use Addressables.Instantiate. Here is my problem. I have a LoadingScreenProvider that inherits from a LocalAssetLoader. 
```csharp
  public class LoadingScreenProvider : LocalAssetLoader, ILoadingProvider
  {
    ...
    public async Task LoadProvider(GameStateEntity entity)
    {
      _entityLoadingProvider = entity;
      _loadingScreen = await Load();
      _entityLoadingProvider.isLoadedProvider = true;
    }

    private Task<LoadingScreen> Load()
    {
      return LoadInternal<LoadingScreen>(_screenLoadingReference);
    }
    ...
}
```


And i have a LocalAssetLoader
```csharp
  public class LocalAssetLoader
  {
    private GameObject _cachedObject;

    protected async Task<T> LoadInternal<T>(AssetReference assetRference)
    {
      var handle = Addressables.InstantiateAsync(assetRference);
      _cachedObject = await handle.Task;
      if (_cachedObject.TryGetComponent(out T component) == false)
        throw new NullReferenceException($"Object of type {typeof(T)} is null on " +
                                         "attempt to load it from addressables");

      return component;
    }

    protected void UnloadInternal()
    {
      if (_cachedObject == null)
        return;
      _cachedObject.SetActive(false);
      Addressables.ReleaseInstance(_cachedObject);
      _cachedObject = null;
    }
}
```

Can you tell me how to use injection in this case?

**Comment by altunsercan** [comment]
After you instantiate using Addressables.Instantitate, pass that GameObject to `Container.InjectGameObject`
https://github.com/modesttree/Zenject/blob/31f06cf81043f04301b1072ec81922b64149ea34/UnityProject/Assets/Plugins/Zenject/Source/Main/DiContainer.cs#L2284

Also you don't appear to be using my system in these code samples. I was trying to help thinking you were using this library. Your problem seems to be related to general Zenject issue. You should try main Zenject issues board or chatrooms for getting support for these problems.

**Comment by DrebotArtem** [comment]
Thanks for the help.
